# Use the base image from continuumio with Miniconda3
FROM continuumio/miniconda3

# Set the working directory within the container
WORKDIR /app

# Install GDAL utilities
RUN apt-get update && apt-get install -y \
    gdal-bin 

# Install unzip utility
RUN apt-get install unzip

# Upgrade pip
RUN pip install --upgrade pip    

# Install JupyterLab using conda from conda-forge channel
RUN conda install -c conda-forge jupyterlab



RUN apt-get update && \
    apt-get install -y docker.io

# Copy Python scripts and files into the /app directory of the container
COPY s2_preprocess.py /app/
COPY image_download_input.py /app/
COPY requirements.txt /app/
COPY sample_data /app/sample_data/

# Install Python packages listed in requirements.txt
RUN pip install -r requirements.txt

# Install additional Python packages pystac and rasterio
# RUN pip install pystac rasterio

RUN mkdir /output
RUN mkdir /shared_files
# Copy the startup script into the /app directory of the container
COPY startup.sh /app/
ENV CONTAINER_NAME=my_container
# Set the entry point for the container to be the startup script
ENTRYPOINT ["/app/startup.sh"]

